fixtures:
  forge_modules:
    stdlib:
      repo: puppetlabs/stdlib
    concat:
      repo: puppetlabs/concat
    firewall:
      repo: puppetlabs/firewall
      ref: '6.0.0'
    yumrepo_core:
      repo: puppetlabs/yumrepo_core
    sudo:
      repo: saz/sudo
    logrotate:
      repo: puppet/logrotate
    augeasproviders_core:
      repo: herculesteam/augeasproviders_core
    augeasproviders_shellvar:
      repo: herculesteam/augeasproviders_shellvar
  symlinks:
    gpfs: "#{source_dir}"
